Adds JS for multiple lessons
a11y-collective/demos pull request #33
Opened 2023-08-10 14:10 UTC by fabiobindels

- First rule
- Dynamic changes
- Accordion

2023-08-17 09:00 UTC, rianrietveld requested changes
Hoi @fabiobindels 
Dank!
Ik heb twee wijzigingen.
Voor de character count wellicht even overleg.

2023-08-17 09:00 UTC, rianrietveld commented on en/aria/first-rule/index.html
>  				<div class="block">
Op deze manier werkt het met toetsenbord nog niet,  addEventListener("keydown"... moet er nog bij.

2023-08-17 09:00 UTC, rianrietveld commented on en/aria/first-rule/index.html
> +					<button class="js-alert">Show alert</button>
voeg class button toe

2023-08-17 09:00 UTC, rianrietveld commented on en/aria/dynamic-changes/index.html
>  					<p id="chars-remaining">
Ik wil dit voor een aria-live demo gebruiken. Dat het zo werkt is prima en kan als basis dienen, maar wat ik eigenlijk wilde laten zien is het volgende:

De output is anders voor visueel and voor auditief.
Dus je ziet gewoon de teller, maar je hoort um niet altijd. Omdat het lastig is bij elke keer de wijziging om je oren te krijgen.

In de oorspronkelijke code was het zo opgezet:
Je krijgt de content te hoen on focus, dan pas weer na 50% van characters met een aria-live="polite" en na 90% van de characters met een aria-live-"assertive".
 
Een gebruikelijke constructie is twee containers:
- een zichtbare met de aria-describedby, die aria-hidden is.
- en een screen-reader-text container met aria-live met wat je wilt announcen. 
Zoals https://designsystem.digital.gov/components/character-count/, maar dan met de check op de hoeveelheid characters.

Misschien moeten we het er even samen over hebben.

2023-08-21 09:01 UTC, fabiobindels commented on en/aria/dynamic-changes/index.html
>  					<p id="chars-remaining">
Ik heb de aria-live updates toegevoegd. Wanneer ik het test met voice-over valt het mij op dat het voorlezen van de updates wordt overruled wanneer er wordt getypt in het veld. Dit gebeurd ook bij `aria-live="assertive"`, ik ben benieuwd hoe we dit kunnen verbeteren.

2023-08-22 13:03 UTC, merged